### ISSUE TITLE
Unable to use Docker Host

### ISSUE THREAD

**Issue by Rudi9719** [monicahq/docker#118]
Not sure if something is missing from the instructions for docker, but when trying to run the docker image I have had 0 success getting the application to work properly. It always ends up trying to connect to resources using the private IP of the host instead of the configured hostname in apache2 and the container. Is there a step I missed?

**Comment by dlardo** [comment]
I just got this working myself. Here is my docker compose if it helps:
```
 monica:
    image: monica
    container_name: monica
    depends_on:
      - monica-db
    environment:
      - TZ=America/Los_Angeles
      - APP_KEY=base64:notActuallyMyPassWord
      - DB_HOST=monica-db
      - DB_USERNAME=monica
      - DB_PASSWORD=yourDBsecret
      - APP_ENV=production
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailout.example.com
      - MAIL_PORT=2025
      - MAIL_USERNAME=smtp@example.com
      - MAIL_PASSWORD=notActuallyMyPassWord
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=monica@example.com
      - MAIL_FROM_NAME="Monica"
      - APP_EMAIL_NEW_USERS_NOTIFICATION=new@example.com
      - APP_URL=https://monica.example.com
    volumes:
    - monica_data:/var/www/html/storage
    ports:
      - 9760:80
    restart: unless-stopped
  monica-db:
    image: mysql:5.7
    container_name: monica-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=yourDBsecret
    volumes:
      - monica_db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  monica_data:
    name: monica_data
  monica_db_data:
    name: monica_db_data
```
