### ISSUE TITLE
Can't get any of the example docker-compose images to work. 

### ISSUE THREAD

**Issue by rdearman** [monicahq/docker#129]
I've tried every example and cannot get any of them to work. The best I have been able to do is get 503 errors. The main problem seems to be that because I'm running another system on 8080 (everything seems to want to use 8080) I need to use a different port. 

Any suggestions for what would be best one to run on a local machine, on a port like 7500, and what I need to change?

**Comment by phattlmann** [comment]
Can you paste your docker.yml file to check out? 
If you need to use another port, select something random like 8183 or whatever. 

Are you hosting this in the cloud, or locally?

**Comment by rdearman** [comment]
version: "3.9"

services:
  app:
    build: ./app
    image: monica-app
    env_file: .env
    volumes:
      - certs:/etc/nginx/certs:ro      
#      - data:/var/www/html/storage
    restart: always
    environment:
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
      - DB_HOST=172.26.0.1:3306
    depends_on:
      - redis
    networks:
      - proxy-tier

  redis:
    image: redis:alpine
    restart: always
    networks:
      - proxy-tier

  cron:
    build: ./app
    image: monica-app
    env_file: .env
    restart: always
    volumes:
      - certs:/etc/nginx/certs:ro      
#      - data:/var/www/html/storage
    command: cron.sh
    depends_on:
      - redis
    networks:
      - proxy-tier

  queue:
    build: ./app
    image: monica-app
    env_file: .env
    restart: always
    volumes:
      - certs:/etc/nginx/certs:ro      
#      - data:/var/www/html/storage
    command: queue.sh
    depends_on:
      - redis
    networks:
      - proxy-tier

  web:
    build: ./web
    image: monica-web
    restart: always
    environment:
      - VIRTUAL_HOST=monica.local
    volumes:
      - certs:/etc/nginx/certs:ro
#      - data:/var/www/html/storage:ro
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 7500:80
      - 7501:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=monica.local
      - CA_SUBJECT=rick@monica.local
      - SSL_KEY=/certs/monica.local.key
      - SSL_CSR=/certs/monica.local.csr
      - SSL_CERT=/certs/monica.local.pem
    networks:
      - proxy-tier

volumes:
#  data:
  certs:

networks:
  proxy-tier:

**Comment by rdearman** [comment]
[docker-compose (copy).yml.txt](https://github.com/monicahq/docker/files/11712464/docker-compose.copy.yml.txt)

I uploaded it as text.

I already have also uploaded .env since I'm using a DB local to the machine.
[env.txt](https://github.com/monicahq/docker/files/11712467/env.txt)

I'm running this (or attempting to) on my local machine. But because I have 4-5 other docker instances running + calibre (which insists on using 8080 as the port) I need a different port. I picked 7500 and 7501 at random.

**Comment by phattlmann** [comment]
Well, it looks like you are running a far more complex setup here than the average person. 

Is there any reason you need a proxy, and to be pushing all these certs, and a queue, and redis? Like, this should really just be 2 containers and off you go. You can try to look at the various log files for each of these containers and see if there's any clues, but really - the YML seems relatively fine without combing through it extensively.

For reference, here's my docker-compose. It's really all you need.....

```
version: "3.4"

services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 8156:80
    environment:
      - APP_KEY=t1YmI32wWPnZz9z8Dj8k20NFaDHG7kyh
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=249e%66igjRe@pMY
    volumes:
      - /volume1/docker/monica/html:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=R!d&dW%k!9sT9Gwe
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=249e%66igjRe@pMY
    volumes:
      - /volume1/docker/monica/mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql
```

Like, you can copy and paste what I have there, and you'd be running on port 8156. Granted, those passwords have been modified from what they actually are. I would suggest when you attach code,  you scrub it for your passwords and login names. One of your files reveals some information I don't think you would generally want anyone to see. Please consider taking it down or maybe modifying your attachments ;)

Anyways, try my docker compose file. Just toss that into a new stack with Portainer and you'll be up. If you need certs or whatever, you should be able to create those in whatever containers handle the certs and your reverse proxy.
