### ISSUE TITLE
Is there a Docker image of the beta version of Monica?

### ISSUE THREAD

**Issue by DonDebonair** [monicahq/docker#142]
I would love to try and run the beta version of Monica (previously known as "Chandler"), but as I understand it, the official Docker images are from the 4.x version of Monica.

Are there Docker images available somewhere of the beta version of Monica? Maybe nightly builds?

I imagine you can use all the help you can get in testing the beta version and providing Docker images for it, would help a great deal with getting people to help you test :)

**Comment by mrodus** [comment]
I haven't tried it myself, but [this](https://github.com/monicahq/monica/discussions/6904#discussioncomment-7263482) might be what you're looking for.

**Comment by slifty** [comment]
It would be really great if 5.x images could be published to docker (including FPM)!

If there is any way I could help make it happen I'd be glad to try.

**Comment by Rayregula** [comment]
I would also like to see a docker image (ideally with a compose file) for 5.x

Did anyone try what @mrodus found?

**Comment by mrodus** [comment]
> I would also like to see a docker image (ideally with a compose file) for 5.x
> 
> Did anyone try what @mrodus found?

I use this and it works just fine for me:
```yaml
  monica:
    container_name: monica
    image: ghcr.io/monicahq/monica-next:main
    restart: unless-stopped
    volumes:
      - ./monica/storage:/var/www/html/storage
    ports:
      - 5858:80
    env_file: monica.env
```

And monica.env:
```env
DB_DATABASE=/var/www/html/storage/database.sqlite
MAIL_MAILER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
MAIL_FROM_ADDRESS=
```
