### ISSUE TITLE
reminder notifications do not work

### ISSUE THREAD

**Issue by pagenstedt** [monicahq/docker#153]
I recently installed monicaHQ (docker compose / apache) and really like it. I have entered my e-mail details in the environment variables of the docker compose file. System messages work perfectly, but the notifications for reminders do not. I have already tried an external cron job 
`* * * * * * cd /opt/monica && docker compose exec -T app php artisan schedule:run >> /dev/null 2>&1`
and also cron in the container itself analogous to [this](https://github.com/monicahq/monica/issues/4758#issuecomment-753387066).
Finally, I followed @cstrat 's advice [here](https://github.com/monicahq/monica/issues/5084#issuecomment-826433532) with built image and setup files.
Unfortunately, with none of those options reminder notifications worked. 
My docker-compose.yml looks like this:

```
services:
  app:
    build: ./setup
    image: monica
    depends_on:
      - db
    ports:
      - 8888:80
    environment:
      - APP_KEY=xxx
      - DB_HOST=db
      - DB_USERNAME=xxx
      - DB_PASSWORD=xxx
      - APP_ENV=production
      - APP_URL=https://xxx
      - MAIL_MAILER=smtp
      - MAIL_HOST=xxx
      - MAIL_PORT=587
      - MAIL_USERNAME=xxx
      - MAIL_PASSWORD=xxx
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=xxx
      - MAIL_FROM_NAME=MonicaHQ
    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=xxx
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxx
    volumes:
      - mysql:/var/lib/mysql
    restart: always


volumes:
  data:
    name: data
  mysql:
    name: mysql
```
