### ISSUE TITLE
How to get past email verification? (monica 5.0.0-beta.4-apache)

### ISSUE THREAD

**Issue by JCBerger** [monicahq/docker#156]
I'm struggling to utilize the docker image (5.0.0-beta.4-apache) because once I navigate to 8080:80, I have to create a username and password. I do that, but then the system says I need to click through the email verification. I realize I'm not going to get an email because there is no email server or account set up, but I don't know how to get past what seems like should be a very simple step. Can someone help me?

**Comment by houxiang676** [comment]
Hi, I have the same problem.  I also cannot pass the email verification step. I use the docker image and set MAIL_MAILER=log, but I don’t know where to find the email log or confirmation code. Did you solve it? Thank you!

**Comment by JCBerger** [comment]
> Hi, I have the same problem. I also cannot pass the email verification step. I use the docker image and set MAIL_MAILER=log, but I don’t know where to find the email log or confirmation code. Did you solve it? Thank you!

Unfortunately, I have not found a workaround. I've even tried to figure out a way to add an account to the database, but haven't been able to figure that out either.

**Comment by zzahkaboom24** [comment]
> > Hi, I have the same problem. I also cannot pass the email verification step. I use the docker image and set MAIL_MAILER=log, but I don’t know where to find the email log or confirmation code. Did you solve it? Thank you!
> 
> Unfortunately, I have not found a workaround. I've even tried to figure out a way to add an account to the database, but haven't been able to figure that out either.

When it did not work for me, the docker logs actually showed me the link that the email would have gotten generated.
However sending mail works for me, here's my docker compose

```
volumes:
  monica_data:
    name: monica_data
  monica-db_data:
    name: monica-db_data

services:
  app:
    image: monica:5.0.0-beta.5-apache
    container_name: Monica
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      - APP_KEY=${APP_KEY}
      - DB_HOST=db:3311
      - DB_USERNAME=monica
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - APP_ENV=local
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_USERNAME=mygmail62@gmail.com
      - MAIL_PASSWORD=xxxx xxxx xxxx xxxx
      - MAIL_ENCRYPTION=ssl
      - MAIL_FROM_ADDRESS=mygmail62@gmail.com
      - MAIL_FROM_NAME=Monica
    volumes:
      - monica_data:/var/www/html/storage
    restart: always
    networks:
      - nginxproxymanager_default

  db:
    image: mariadb:11.4
    container_name: MonicaMariaDB
    environment:
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_TCP_PORT=3311
    volumes:
      - monica-db_data:/var/lib/mysql
    restart: always
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
    name: nginxproxymanager_default
```
