### ISSUE TITLE
[Beta] Unsupported cipher or incorrect key length

### ISSUE THREAD

**Issue by mrvaghani** [monicahq/docker#159]
Docker Image: monica:5.0.0-beta.5-apache

Setup new docker compose like below:

```
#docker-compose.yml
services:
  app:
    image: monica:5.0.0-beta.5-apache
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - APP_KEY=J9Uq3kdfaQ6H3fJE+zCPGyNT4uNzqITAE4Eee/qxUXA=
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=secret
    volumes:
      - "./data:/var/www/html/storage"
    restart: always

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql

```

Run `docker compose up -d`
Follow logs to see when setup is ready `docker compose logs -f`

Once the app is up, visit [http://localhost:8080/](http://localhost:8080/)

Snippet of relevant error in docker logs:

```
app-1  | [2025-06-07 00:51:25] production.ERROR: Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm. {"exception":"[object] (RuntimeException(code: 0): Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:61)
app-1  | [stacktrace]
app-1  | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\Encrypter->__construct('J9Uq3kdfaQ6H3fJ...', 'AES-256-CBC')
app-1  | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1010): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
app-1  | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(890): Illuminate\\Container\\Container->build(Object(Closure))
app-1  | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1077): Illuminate\\Container\\Container->resolve('encrypter', Array, true)
app-1  | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(821): Illuminate\\Foundation\\Application->resolve('encrypter', Array)
app-1  | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1057): Illuminate\\Container\\Container->make('encrypter', Array)
app-1  | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1202): Illuminate\\Foundation\\Application->make('encrypter')
app-1  | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1101): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
app-1  | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1052): Illuminate\\Container\\Container->resolveDependencies(Array)
app-1  | #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(890): Illuminate\\Container\\Container->build('Illuminate\\\\Cook...')
app-1  | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1077): Illuminate\\Container\\Container->resolve('Illuminate\\\\Cook...', Array, true)
app-1  | #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(821): Illuminate\\Foundation\\Application->resolve('Illuminate\\\\Cook...', Array)
app-1  | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1057): Illuminate\\Container\\Container->make('Illuminate\\\\Cook...', Array)
app-1  | #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(257): Illuminate\\Foundation\\Application->make('Illuminate\\\\Cook...')
app-1  | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
app-1  | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1221): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
app-1  | #16 /var/www/html/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
app-1  | #17 {main}
app-1  | "}
app-1  | 172.20.0.1 - - [07/Jun/2025:00:51:25 +0000] "GET / HTTP/1.1" 500 13493 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0
```

Other (unrelated?) things to note:
The error I get when I follow documentation to run `docker exec` command

```
D:\docker-apps\Monica>docker compose exec app php artisan setup:production
[2025-06-07 00:50:16] production.ERROR: There are no commands defined in the "setup" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"setup\" namespace. at /var/www/html/vendor/symfony/console/Application.php:660)
[stacktrace]
#0 /var/www/html/vendor/symfony/console/Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('setup')
#1 /var/www/html/vendor/symfony/console/Application.php(284): Symfony\\Component\\Console\\Application->find('setup:productio...')
#2 /var/www/html/vendor/symfony/console/Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1234): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 /var/www/html/artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"}

   ERROR  There are no commands defined in the "setup" namespace.
```
