### ISSUE TITLE
APP_URL for reverse proxy subfolder

### ISSUE THREAD

**Issue by IronicBadger** [monicahq/docker#32]
I'm attempting to load Monica at `my.domain.com/subfolder` and not having any luck the `APP_URL` or `APP_FORCE_URL` parameter in the Apache image.

A sanitized docker-compose is here:

```
  monica:
    image: monica
    container_name: monica
    volumes:
      - /mnt/tank/appdata/monica/app:/var/www/html/storage
    labels:
      - traefik.enable=true
      - traefik.http.routers.monica.rule=(Host(`my.domain.com`) && PathPrefix(`/monica`))
      - traefik.http.routers.monica.entrypoints=websecure
      - traefik.http.routers.monica.tls.certresolver=cloudflare
      - traefik.http.services.monica.loadbalancer.server.port=80
    ports:
      - 8901:80
    environment:
      - APP_KEY=32char
      - APP_URL=monica
      - APP_FORCE_URL=true
      - DB_HOST=db
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mariadb
    container_name: db
    volumes:
      - /mnt/tank/appdata/monica/db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
    restart: unless-stopped
```

<img width="271" alt="image" src="https://user-images.githubusercontent.com/2773080/93415995-c39c9300-f872-11ea-8d59-14a59af197f4.png">

The above image is error I get. It appears that this docker image doesn't use the specified URL to make paths available at the correct location. The app works fine at `ip:port`.
