### ISSUE TITLE
Monica does not send reminders or stay_in_touch mails

### ISSUE THREAD

**Issue by peetersdaan** [monicahq/docker#48]
First and foremost thank you guys for creating Monica!

Currently I'm trying to run the Monica Supervisor [Apache](https://github.com/monicahq/docker/tree/master/.examples/supervisor/apache) on my Synology DS418 Play. 

`php artisan monica:test-email` works.
`php artisan send:stay_in_touch `and `php artisan send:reminders` do not.

My docker compose:

```
version: "3.4"

services:
  app:
    build: ./app
    image: monica-app
    depends_on:
      - db
    environment:
      - APP_KEY=**** 
      - DB_HOST=db
      - TZ=Amsterdam/Europe
      - MAIL_MAILER=smtp
      - MAIL_HOST=****
      - MAIL_PORT=****
      - MAIL_ENCRYPTION=****
      - MAIL_USERNAME=****
      - MAIL_PASSWORD=****
      - MAIL_FROM_ADDRESS=****
      - MAIL_FROM_NAME="Monica Personal CRM"
      - APP_URL=****
      - QUEUE_CONNECTION=database
      - PUID=1026
      - GUID=101
    ports:
      - 8080:80
    volumes:
      - ****:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - ****:/var/lib/mysql
    restart: always
```

Screenshots from the log:
![Screenshot 2021-04-23 at 19 27 19](https://user-images.githubusercontent.com/53089641/115908086-fd1d2880-a469-11eb-837a-6bb359357b62.jpg)

How can I fix this issue?
