### ISSUE TITLE
running from portainer

### ISSUE THREAD

**Issue by kavemang** [monicahq/docker#69]
Hi, if running this compose from portainer is there an alternate instruction set? 

I've tried both with and without the final step "docker-compose exec app php artisan setup:production" but haven't been able to get it actually running, the closest I've gotten is creating a login profile on the local page at which point I get an error message

**Comment by chmac** [comment]
It runs fine for me. You just need a `docker-compose.yml` file, something like:

```yml
version: "3.4"

services:
  app:
    image: monica:apache
    depends_on:
      - db
    ports:
      - 3400:80
    environment:
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=monica
      - APP_ENV=production
      - APP_DISABLE_SIGNUP=true
    volumes:
      - /opt/monica/storage:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=monica
    volumes:
      - /opt/monica/mysql:/var/lib/mysql
    restart: always
```

That runs monica on port 4100 without SSL.
