### ISSUE TITLE
DB container replaces volume during watchtower update

### ISSUE THREAD

**Issue by kavemang** [monicahq/docker#92]
Hi folks, it looks like whenever watchtower updates the mysql container for monica it's creating a new volume and to get the DB back up I'm manually reassigning the original volume, can I get advice on how to prevent that (besides disabling watch tower, or maybe I should look into excluding the mysql container in some way) 

my compose: 

```
services:
  monica:
    image: monica:3.0.1-apache
    depends_on:
      - monica-db
    container_name: monica_personal
    ports:
      - 8091:80
    environment:
      - APP_KEY=base64:klkdjflskdjfalskdflksdfjlaskojf?????0E=
      - DB_HOST=monica-db
      - DB_USERNAME=monica
      - DB_PASSWORD=passwordmatch
      - APP_TRUSTED_PROXIES="*"
      - APP_URL=https://monica.example.com
    # volumes:
    #   - data:/var/www/html/storage
    restart: unless-stopped


  monica-db:
    image: mysql:5.7
    container_name: monica-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=passwordmatch
    # volumes:
    #   - mysql:/var/lib/mysql
    restart: unless-stopped
```
